### PR TITLE
Chapter 8 Notes

### PR DESCRIPTION
**Pull request by vrindaprabhu**
Adding notes for Chapter-8, PCA and LLE. 
Followed the template in Chapter-7.

### CODE REVIEW

**Comment by jaganseshadri** [comment]
The notes look nice. 

Can we have a CONTRIBUTING.md file like in [here](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md)? Not so comprehensive. 
I'd prefer we keep the contents as is but push it in markdown.

**Comment by jaganseshadri** [comment]
Also on the notes side I'd like to separate the intuition from the math and code. So that it doesn't drag the revision/learning.

**Comment by vrindaprabhu** [comment]
I agree on separating the math section from the intuition. Once the template is finalized, will edit accordingly.
Also changed the name of the current notes.

**Review by jaganseshadri — APPROVED** [review]
LGTM. Will merge now. Later will separate out the code and math

**Pull request merged**
